### PR TITLE
Add Linux compiling support

### PR DESCRIPTION
**Pull request by Jaffies**
It's not really tested, cuz after launching hl2_launcher, for some reason i get  'Setup file 'gameinfo.txt' doesn't exist in subdirectory', but at least it manages to compile, after all.

### CODE REVIEW

**Comment by Jaffies** [comment]
Nevermind, i was launching hl2_launcher from different path, i launched the correct one, and now it starts

**Comment by relt-1** [comment]
Why was this closed?

**Comment by Jaffies** [comment]
Maybe it breaks windows support idk, you should try to compile that on msvc and create server.
In my case on linux there's a segmentation fail error after trying to enter map.
If someone would debug and fix this, then it would be really nice.

**Comment by relt-1** [comment]
ill get to it, dw

**Pull request closed without merging**
